import React from 'react';
import { Activity, AlertTriangle, Car, CheckCircle2, CircleDollarSign, RefreshCw, Route, Star, Users, WalletCards } from 'lucide-react';
import { coreApiRequest } from './coreApi.js';
import { money, normalizeServiceCode, paymentStatusGroup, isSameLocalDay } from './analyticsModel.js';
import { PageError, PageLoading, PageEmpty } from './AdminPageState.jsx';

const STATUS_LABEL={COMPLETED:'Hoàn thành',IN_PROGRESS:'Đang chạy',DRIVER_ASSIGNED:'Đã gán tài xế',SEARCHING:'Đang tìm',CANCELLED:'Đã hủy'};
function Kpi({icon:Icon,label,value,sub,tone=''}){return <article className={`enterprise-kpi ${tone}`}><span className="enterprise-kpi-icon"><Icon size={20}/></span><div><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div></article>}
export default function DashboardPage(){
  const [data,setData]=React.useState(null);const [live,setLive]=React.useState([]);const [loading,setLoading]=React.useState(true);const [error,setError]=React.useState('');
  const load=React.useCallback(async()=>{setLoading(true);setError('');try{const [a,d]=await Promise.all([coreApiRequest('/api/v14/admin/analytics?days=14'),coreApiRequest('/api/v7/admin/drivers/live?limit=300').catch(()=>[])]);setData(a);setLive(Array.isArray(d)?d:[])}catch(e){setError(e.message||String(e))}finally{setLoading(false)}},[]);
  React.useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>window.clearInterval(t)},[load]);
  if(loading&&!data)return <PageLoading text="Đang tải Dashboard TrackAsia..."/>; if(error&&!data)return <PageError message={error} onRetry={load}/>;
  const trips=data?.trips||[];const today=trips.filter(x=>isSameLocalDay(x.completedAt||x.createdAt));const completedToday=today.filter(x=>String(x.status).toUpperCase()==='COMPLETED');const grossToday=completedToday.reduce((s,x)=>s+Number(x.customerTotal||0),0);const todayPoints=completedToday.reduce((s,x)=>s+Number(x.pointsAwarded||x.loyaltyPoints||0),0);const online=live.filter(x=>['ONLINE','BUSY'].includes(String(x.onlineStatus||'').toUpperCase())).length;const k=data?.kpis||{};const days=data?.byDay||[];const max=Math.max(1,...days.map(x=>Number(x.gross||0)));const recent=[...trips].reverse().slice(0,7);
  return <section className="enterprise-page dashboard-enterprise"><header className="enterprise-page-head dashboard-control-header"><div><span className="enterprise-eyebrow">TH79 iMOVE · LIVE CONTROL CENTER</span><h1>Tổng quan vận hành</h1><p>Dữ liệu thật từ Core Backend 1.4.0, bookings, payments, ledger và GPS tài xế.</p></div><button type="button" className="button" onClick={load}><RefreshCw size={15}/>Làm mới</button></header>{error&&<div className="v73-alert"><AlertTriangle size={15}/> {error}</div>}
    <div className="enterprise-kpi-grid dashboard-kpi-strip"><Kpi icon={Route} label="Tổng chuyến hôm nay" value={today.length} sub={`${completedToday.length} hoàn thành`}/><Kpi icon={Activity} label="Tài xế Online" value={online} sub={`${live.length} bản ghi live`}/><Kpi icon={WalletCards} label="Doanh thu hôm nay" value={money(grossToday)} sub="Chuyến COMPLETED"/><Kpi icon={CircleDollarSign} label="Settlement backlog" value={Number(k.settlementBacklog||0)} tone={Number(k.settlementBacklog||0)>0?'warn':''}/><Kpi icon={Star} label="Điểm phát sinh hôm nay" value={todayPoints} sub="Theo dữ liệu booking hiện có"/></div>
    <div className="enterprise-dashboard-grid"><section className="card enterprise-panel chart-panel"><header><div><h2>Doanh thu theo ngày</h2><p>14 ngày gần nhất</p></div><b>{money(k.grossFare)}</b></header>{days.length?<div className="enterprise-bars">{days.map(x=><div className="enterprise-bar" key={x.date} title={`${x.date}: ${money(x.gross)}`}><span style={{height:`${Math.max(5,Number(x.gross||0)/max*100)}%`}}></span><small>{String(x.date).slice(5)}</small></div>)}</div>:<PageEmpty title="Chưa có doanh thu" description="Chưa có chuyến hoàn thành trong kỳ báo cáo."/>}</section>
    <section className="card enterprise-panel"><header><div><h2>Cơ cấu dịch vụ</h2><p>Theo serviceCode chuẩn hóa</p></div><Car size={18}/></header><div className="enterprise-service-list">{(data?.services||[]).map(x=><div key={x.serviceCode}><span><b>{x.serviceName||normalizeServiceCode(x)}</b><small>{x.completed||0}/{x.trips||0} chuyến hoàn thành</small></span><strong>{money(x.gross)}</strong></div>)}{!(data?.services||[]).length&&<PageEmpty/>}</div></section></div>
    <div className="enterprise-dashboard-grid"><section className="card enterprise-panel"><header><div><h2>Chuyến gần đây</h2><p>Trạng thái cập nhật từ Backend</p></div><Route size={18}/></header><div className="enterprise-table-wrap"><table><thead><tr><th>Mã</th><th>Dịch vụ</th><th>Trạng thái</th><th>Khách trả</th></tr></thead><tbody>{recent.map(x=><tr key={x.id}><td><code>{String(x.id).slice(-8)}</code></td><td>{normalizeServiceCode(x)}</td><td><span className={`v14-status ${String(x.status).toUpperCase()==='COMPLETED'?'success':'pending'}`}>{STATUS_LABEL[String(x.status).toUpperCase()]||x.status||'—'}</span></td><td><b>{money(x.customerTotal)}</b></td></tr>)}</tbody></table></div></section>
    <section className="card enterprise-panel"><header><div><h2>Thanh toán & hệ thống</h2><p>Tổng hợp nhanh</p></div><CheckCircle2 size={18}/></header><div className="enterprise-mini-stats"><div><span>PAID</span><b>{(data?.payments||[]).filter(x=>paymentStatusGroup(x.status)==='success').length}</b></div><div><span>Chuyến hoàn thành</span><b>{k.completed||0}</b></div><div><span>Platform revenue</span><b>{money(k.platformRevenue)}</b></div><div><span>Driver net</span><b>{money(k.driverNet)}</b></div></div></section></div>
  </section>;
}
