import React from 'react';
import { RefreshCw, RadioTower, Send, RotateCcw, TimerReset, BellRing, Ban, Save } from 'lucide-react';
import { coreApiRequest } from './coreApi.js';

const box={background:'#fff',border:'1px solid #e7e9ed',borderRadius:18,padding:16,boxShadow:'0 8px 24px rgba(16,24,40,.04)'};
const btn={border:'1px solid #dfe3e8',background:'#fff',borderRadius:10,padding:'8px 11px',fontWeight:800,cursor:'pointer',display:'inline-flex',gap:6,alignItems:'center'};
const primary={...btn,background:'#d71920',color:'#fff',borderColor:'#d71920'};

export default function DispatchCenterPage(){
  const [cfg,setCfg]=React.useState(null);const [live,setLive]=React.useState([]);const [push,setPush]=React.useState({stats:{},rows:[]});const [cooldowns,setCooldowns]=React.useState([]);const [selected,setSelected]=React.useState(null);const [detail,setDetail]=React.useState(null);const [error,setError]=React.useState('');const [message,setMessage]=React.useState('');
  const load=React.useCallback(async()=>{setError('');try{const [c,l,p,cd]=await Promise.all([coreApiRequest('/api/v69/admin/dispatch/config'),coreApiRequest('/api/v69/admin/dispatch/live'),coreApiRequest('/api/v69/admin/dispatch/push?limit=100'),coreApiRequest('/api/v69/admin/dispatch/cooldowns')]);setCfg(c);setLive(Array.isArray(l)?l:[]);setPush(p||{stats:{},rows:[]});setCooldowns(Array.isArray(cd)?cd:[]);}catch(e){setError(e.message)}},[]);
  React.useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[load]);
  async function open(id){setSelected(id);try{setDetail(await coreApiRequest(`/api/v69/admin/dispatch/bookings/${id}`))}catch(e){setError(e.message)}}
  async function act(path,body){setError('');setMessage('');try{await coreApiRequest(path,{method:'POST',body:JSON.stringify(body||{})});setMessage('Đã thực hiện.');await load();if(selected)await open(selected);}catch(e){setError(e.message)}}
  async function save(){try{await coreApiRequest('/api/v69/admin/dispatch/config',{method:'PUT',body:JSON.stringify(cfg)});setMessage('Đã lưu cấu hình điều phối.');await load()}catch(e){setError(e.message)}}
  return <div>
    <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'end',flexWrap:'wrap',marginBottom:16}}><div><div style={{fontSize:12,color:'#d71920',fontWeight:900}}>NOTIFICATION & DISPATCH ENGINE</div><h1 style={{margin:'4px 0'}}>Live Dispatch & FCM</h1><p style={{margin:0,color:'#777'}}>Phát đơn theo vòng, timeout, retry, cooldown và chống gửi trùng.</p></div><div style={{display:'flex',gap:8}}><button style={btn} onClick={load}><RefreshCw size={15}/>Tải lại</button><button style={primary} onClick={save}><Save size={15}/>Lưu cấu hình</button></div></div>
    {error&&<div style={{background:'#fff0f0',color:'#b42318',padding:12,borderRadius:12,marginBottom:10,fontWeight:700}}>{error}</div>}{message&&<div style={{background:'#edf9f1',color:'#137a43',padding:12,borderRadius:12,marginBottom:10,fontWeight:700}}>{message}</div>}
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,marginBottom:14}}>{[['Chuyến live',live.length,RadioTower],['Push SENT',push.stats?.SENT||0,BellRing],['Push FAILED',push.stats?.FAILED||0,Ban],['Cooldown',cooldowns.length,TimerReset]].map(([l,v,I])=><div key={l} style={box}><I size={18}/><div style={{fontSize:28,fontWeight:900,marginTop:8}}>{v}</div><div style={{color:'#777',fontWeight:700}}>{l}</div></div>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'minmax(340px,.8fr) minmax(0,1.2fr)',gap:12,alignItems:'start'}}>
      <div style={{display:'grid',gap:12}}><section style={box}><h2 style={{marginTop:0}}>Cấu hình vòng</h2><label style={{display:'flex',gap:8,alignItems:'center',fontWeight:800,marginBottom:10}}><input type="checkbox" checked={cfg?.enabled!==false} onChange={e=>setCfg(c=>({...c,enabled:e.target.checked}))}/>Bật hệ thống điều phối</label>{(cfg?.rounds||[]).map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'40px 1fr 1fr 1fr',gap:7,alignItems:'end',marginBottom:8}}><b>R{i+1}</b>{[['candidateCount','Driver'],['radiusKm','Km'],['timeoutSeconds','Giây']].map(([k,l])=><label key={k} style={{fontSize:11,fontWeight:800}}>{l}<input type="number" value={r[k]} onChange={e=>setCfg(c=>({...c,rounds:c.rounds.map((x,j)=>j===i?{...x,[k]:Number(e.target.value)}:x)}))} style={{width:'100%',boxSizing:'border-box',padding:8,border:'1px solid #ddd',borderRadius:8}}/></label>)}</div>)}<h3>Cooldown</h3>{Object.entries(cfg?.cooldown||{}).map(([k,v])=><label key={k} style={{display:'grid',gridTemplateColumns:'1fr 100px',gap:8,alignItems:'center',fontSize:12,fontWeight:800,marginBottom:7}}><span>{k}</span><input type="number" value={v} onChange={e=>setCfg(c=>({...c,cooldown:{...c.cooldown,[k]:Number(e.target.value)}}))} style={{padding:8,border:'1px solid #ddd',borderRadius:8}}/></label>)}<h3>Retry Dispatch</h3><label style={{display:'grid',gridTemplateColumns:'1fr 100px',gap:8,alignItems:'center',fontSize:12,fontWeight:800,marginBottom:7}}><span>Số lần retry</span><input type="number" value={cfg?.retry?.maxDispatchRetries??3} onChange={e=>setCfg(c=>({...c,retry:{...(c.retry||{}),maxDispatchRetries:Number(e.target.value)}}))} style={{padding:8,border:'1px solid #ddd',borderRadius:8}}/></label><label style={{display:'grid',gap:5,fontSize:12,fontWeight:800}}><span>Delay (giây, phân cách dấu phẩy)</span><input value={(cfg?.retry?.retryDelaySeconds||[3,10,30]).join(',')} onChange={e=>setCfg(c=>({...c,retry:{...(c.retry||{}),retryDelaySeconds:e.target.value.split(',').map(x=>Number(x.trim())||1)}}))} style={{padding:8,border:'1px solid #ddd',borderRadius:8}}/></label></section>
      <section style={box}><h2 style={{marginTop:0}}>Cooldown đang hoạt động</h2>{cooldowns.slice(0,20).map(c=><div key={c.id} style={{padding:'8px 0',borderTop:'1px solid #eee',fontSize:12,display:'grid',gridTemplateColumns:'1fr auto',gap:8,alignItems:'center'}}><div><b>{c.type}</b> · Driver {String(c.driverId).slice(-7)}<div>{new Date(c.expiresAt).toLocaleString('vi-VN')}</div></div><button style={btn} onClick={()=>coreApiRequest(`/api/v69/admin/dispatch/cooldowns/${encodeURIComponent(c.driverId)}`,{method:'DELETE'}).then(load).catch(e=>setError(e.message))}>Reset</button></div>)}</section></div>
      <div style={{display:'grid',gap:12}}><section style={{...box,padding:0,overflow:'hidden'}}><div style={{padding:14,borderBottom:'1px solid #eee'}}><h2 style={{margin:0}}>Live Dispatch</h2></div><div style={{maxHeight:430,overflow:'auto'}}>{live.map(b=><button key={b.id} onClick={()=>open(b.id)} style={{width:'100%',textAlign:'left',border:0,borderTop:'1px solid #f0f1f3',background:selected===b.id?'#fff5f5':'#fff',padding:13,cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between'}}><b>{b.code}</b><span>{b.status}</span></div><div style={{fontSize:12,color:'#777',marginTop:4}}>{b.pickup} → {b.destination}</div><div style={{fontSize:11,color:'#999'}}>Round {b.dispatchV69?.currentRound||0} · {b.dispatchV69?.status||'—'}</div></button>)}</div></section>
      {detail&&<section style={box}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><h2 style={{margin:0}}>Chi tiết Dispatch</h2><div style={{display:'flex',gap:6}}><button style={btn} onClick={()=>act(`/api/v69/admin/dispatch/bookings/${selected}/next-round`)}><Send size={14}/>Vòng tiếp</button><button style={btn} onClick={()=>act(`/api/v69/admin/dispatch/bookings/${selected}/retry`)}><RotateCcw size={14}/>Retry</button><button style={btn} onClick={()=>act(`/api/v69/admin/dispatch/bookings/${selected}/cancel-offers`)}><Ban size={14}/>Hủy offer</button></div></div><div style={{marginTop:12,display:'grid',gap:6}}>{(detail.offers||[]).map(o=><div key={o._id||o.id} style={{display:'grid',gridTemplateColumns:'55px 1fr 90px 90px',gap:8,padding:9,border:'1px solid #eee',borderRadius:10,fontSize:12}}><b>R{o.round}</b><span>Driver {String(o.driverId).slice(-8)} · score {o.matchingScore??'—'}</span><b>{o.status}</b><span>{o.expiresAt?new Date(o.expiresAt).toLocaleTimeString('vi-VN'):'—'}</span></div>)}</div><h3>Timeline</h3>{(detail.events||[]).slice(-30).map((e,i)=><div key={i} style={{fontSize:12,padding:'6px 0',borderTop:'1px solid #f2f2f2'}}><b>{e.event}</b> · {e.createdAt?new Date(e.createdAt).toLocaleString('vi-VN'):''}</div>)}</section>}
      <section style={{...box,padding:0,overflow:'hidden'}}><div style={{padding:14,borderBottom:'1px solid #eee'}}><h2 style={{margin:0}}>FCM Push Monitor</h2><small>Configured: {String(Boolean(push.configured))}</small></div><div style={{maxHeight:320,overflow:'auto'}}>{(push.rows||[]).slice(0,50).map(x=><div key={x.id} style={{padding:10,borderTop:'1px solid #f0f1f3',fontSize:12,display:'grid',gridTemplateColumns:'1fr auto',gap:8,alignItems:'center'}}><div><b>{x.type} · {x.status}</b><div>{x.title} — {x.body}</div><small>{x.lastError||''}</small></div>{['FAILED','RETRY','NO_DEVICE'].includes(x.status)&&<button style={btn} onClick={()=>act(`/api/v69/admin/dispatch/push/${x.id}/retry`)}>Retry Push</button>}</div>)}</div></section></div>
    </div>
  </div>
}
