const groups=[
 {label:'Vận hành',permissions:[['dashboard.view','Xem Dashboard'],['bookings.view','Xem chuyến xe'],['bookings.adjust','Can thiệp chuyến'],['matching.view','Xem Matching'],['matching.manage','Quản lý Matching'],['drivers.view','Xem tài xế'],['drivers.review','Duyệt KYC'],['users.view','Xem khách hàng']]},
 {label:'Kinh doanh',permissions:[['services.view','Xem dịch vụ'],['services.manage','Quản lý dịch vụ'],['pricing.view','Xem giá cước'],['pricing.manage','Quản lý giá cước'],['promotions.view','Xem khuyến mãi'],['promotions.manage','Quản lý khuyến mãi'],['payments.view','Xem thanh toán'],['reports.view','Xem báo cáo'],['settlements.view','Xem đối soát']]},
 {label:'Chăm sóc khách hàng',permissions:[['support.view','Xem Chat Support'],['support.assign','Nhận/phân công hội thoại'],['support.reply','Phản hồi người dùng'],['support.close','Đóng/mở hội thoại']]},
 {label:'Truyền thông',permissions:[['broadcast.view','Xem thông báo'],['broadcast.manage','Phát thông báo']]},
 {label:'An toàn',permissions:[['trust.view','Xem Trust & Safety'],['trust.review','Duyệt Trust & Safety'],['trust.manage','Quản lý Trust & Safety']]},
 {label:'Hệ thống',permissions:[['settings.view','Xem cài đặt'],['settings.manage','Quản lý cài đặt'],['admins.view','Xem tài khoản nội bộ'],['admins.manage','Sửa tài khoản nội bộ'],['roles.manage','Quản lý phân quyền'],['audit.view','Xem lịch sử thao tác']]},
];
export function permissionGroups(extra=[]){const seen=new Set(groups.flatMap(g=>g.permissions.map(([code])=>code)));const result=groups.map(g=>({label:g.label,permissions:g.permissions.map(([code,label])=>({code,label}))}));const unknown=(Array.isArray(extra)?extra:[]).filter(code=>code&&!seen.has(code)).map(code=>({code,label:code}));if(unknown.length)result.push({label:'Khác',permissions:unknown});return result;}
