import React from 'react';
import { RefreshCw, Search, Route, WalletCards, Tag, Clock3 } from 'lucide-react';
import { coreApiRequest } from './coreApi.js';
import { safeDisplay, numberValue } from './uiModel.js';
import { money, normalizeServiceCode } from './analyticsModel.js';
import { PageEmpty, PageError, PageLoading } from './AdminPageState.jsx';
import TripOperationsMap from './TripOperationsMap.jsx';

function time(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('vi-VN')}
export default function TripsPage(){
 const [rows,setRows]=React.useState([]);const [query,setQuery]=React.useState('');const [status,setStatus]=React.useState('ALL');const [service,setService]=React.useState('ALL');const [selected,setSelected]=React.useState(null);const [loading,setLoading]=React.useState(true);const [error,setError]=React.useState('');
 const load=React.useCallback(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams({limit:'200'});if(query.trim())p.set('q',query.trim());if(status!=='ALL')p.set('status',status);const d=await coreApiRequest(`/api/v7/admin/bookings?${p}`);setRows(Array.isArray(d)?d:[])}catch(e){setError(e.message||String(e))}finally{setLoading(false)}},[query,status]);React.useEffect(()=>{load()},[]);
 const visible=rows.filter(r=>service==='ALL'||normalizeServiceCode(r)===service);const services=[...new Set(rows.map(normalizeServiceCode).filter(x=>x!=='UNKNOWN'))];
 async function open(row){setSelected({row,loading:true});try{const d=await coreApiRequest(`/api/v7/admin/bookings/${encodeURIComponent(row.id)}`);setSelected({row,data:d,loading:false})}catch(e){setSelected({row,error:e.message,loading:false})}}
 if(loading&&!rows.length)return <PageLoading text="Đang tải chuyến xe..."/>;if(error&&!rows.length)return <PageError message={error} onRetry={load}/>;
 return <section className="enterprise-page"><header className="enterprise-page-head"><div><span className="enterprise-eyebrow">TRIP OPERATIONS</span><h1>Chuyến xe</h1><p>Theo dõi booking, Dịch vụ, Thanh toán, Settlement và Timeline trên một màn hình.</p></div><button className="button" onClick={load}><RefreshCw size={15}/>Làm mới</button></header>
 <section className="card enterprise-panel"><div className="enterprise-toolbar"><label className="enterprise-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Mã chuyến, điểm đón, điểm đến..."/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Tất cả trạng thái</option>{['SEARCHING','DRIVER_ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select><select value={service} onChange={e=>setService(e.target.value)}><option value="ALL">Tất cả dịch vụ</option>{services.map(x=><option key={x}>{x}</option>)}</select><button className="button" onClick={load}>Tìm</button></div><div className="enterprise-table-wrap"><table><thead><tr><th>Mã chuyến</th><th>Dịch vụ</th><th>Trạng thái</th><th>Điểm đón → Điểm đến</th><th>Thanh toán</th><th>Settlement</th><th>Thời gian</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} onClick={()=>open(r)} className="clickable-row"><td><b>{safeDisplay(r.code||r.bookingCode||r.id)}</b></td><td>{normalizeServiceCode(r)}</td><td><span className={`v14-status ${String(r.status).toUpperCase()==='COMPLETED'?'success':'pending'}`}>{safeDisplay(r.status)}</span></td><td><b>{safeDisplay(r.pickup)}</b><small className="v14-subline">→ {safeDisplay(r.destination)}</small></td><td>{safeDisplay(r.paymentStatus)}</td><td>{safeDisplay(r.settlementStatus||r.settlementV140?.status||r.settlementV133?.status,'PENDING')}</td><td>{time(r.createdAt)}</td></tr>)}</tbody></table></div>{!visible.length&&<PageEmpty/>}</section>
 {selected&&<div className="enterprise-drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="enterprise-drawer wide" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><span className="enterprise-eyebrow">TRIP DETAIL</span><h2>{safeDisplay(selected.row.code||selected.row.id)}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></header>{selected.loading?<PageLoading/>:selected.error?<PageError message={selected.error}/>:<><TripOperationsMap trips={[{...selected.data?.booking,id:selected.row.code||selected.row.id,pickup:selected.row.pickup,destination:selected.row.destination}]}/><div className="enterprise-detail-grid"><div><span>Dịch vụ</span><b><Route size={15}/>{normalizeServiceCode(selected.data?.booking||selected.row)}</b></div><div><span>Thanh toán</span><b><WalletCards size={15}/>{safeDisplay(selected.data?.booking?.paymentStatus||selected.row.paymentStatus)}</b></div><div><span>Settlement</span><b><Tag size={15}/>{safeDisplay(selected.data?.booking?.settlementV140?.status||selected.data?.booking?.settlementV133?.status,'PENDING')}</b></div><div><span>Khách trả</span><b>{money(numberValue(selected.data?.booking?.pricing?.customerTotal??selected.row.customerTotal,0))}</b></div></div><section className="enterprise-subsection"><h3>Timeline</h3>{(selected.data?.events||[]).map(e=><div className="enterprise-list-row" key={e.id}><span><b>{safeDisplay(e.type)}</b><small><Clock3 size={11}/>{time(e.createdAt)}</small></span></div>)}{!(selected.data?.events||[]).length&&<PageEmpty/>}</section></>}</aside></div>}
 </section>;
}
