import React from 'react';
import { ShieldCheck, TriangleAlert, ScanFace, Smartphone, MapPinned, Ban, RefreshCw, CheckCircle2, XCircle, Radar, Fingerprint } from 'lucide-react';
import { adminAccessToken } from './adminApi.js';
import { PermissionDenied, PageError } from './AdminPageState.jsx';
import { coreUrl } from './apiRuntime.js';

async function core(path,options={}){const r=await fetch(coreUrl(`/api/admin/v70/trust${path}`),{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${adminAccessToken()}`,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`API ${r.status}`);return d}
const fmt=v=>new Intl.NumberFormat('vi-VN').format(Number(v||0)); const date=v=>v?new Date(v).toLocaleString('vi-VN'):'—';
export default function TrustSafetyPage(){
  const [overview,setOverview]=React.useState({}); const [events,setEvents]=React.useState([]); const [cases,setCases]=React.useState([]); const [verify,setVerify]=React.useState([]); const [profiles,setProfiles]=React.useState([]); const [devices,setDevices]=React.useState([]); const [rules,setRules]=React.useState([]); const [tab,setTab]=React.useState('events'); const [busy,setBusy]=React.useState(false); const [error,setError]=React.useState('');
  async function load(){setBusy(true);setError('');try{const [o,e,c,v,p,d,r]=await Promise.all([core('/overview'),core('/events?limit=120'),core('/cases'),core('/verifications'),core('/profiles'),core('/devices'),core('/rules')]);setOverview(o);setEvents(e);setCases(c);setVerify(v);setProfiles(p);setDevices(d);setRules(r)}catch(e){setError(e.message)}finally{setBusy(false)}}
  React.useEffect(()=>{load()},[]);
  async function review(id,decision){await core(`/verifications/${id}/review`,{method:'POST',body:JSON.stringify({decision})});await load()}
  async function caseAction(id,action){await core(`/cases/${id}/action`,{method:'POST',body:JSON.stringify({action})});await load()}
  async function openEvidence(id){const r=await fetch(coreUrl(`/api/admin/v70/trust/verifications/${id}/evidence`),{headers:{Authorization:`Bearer ${adminAccessToken()}`}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||'Không mở được evidence');}const url=URL.createObjectURL(await r.blob());window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}
  async function revokeDevice(id){await core(`/devices/${id}/revoke`,{method:'POST',body:'{}'});await load()}
  async function updateRule(rule,patch){await core(`/rules/${rule._id}`,{method:'PUT',body:JSON.stringify(patch)});await load()}
  if(error&&/403|quyền|permission/i.test(error)) return <PermissionDenied message={error}/>;
  if(error&&/network|fetch|core backend|connection|refused/i.test(error)) return <PageError message={error} onRetry={load}/>;
  const stat=[['Risk events hôm nay',overview.todayRiskEvents,TriangleAlert,'red'],['High risk',overview.highRiskEvents,Radar,'amber'],['Face chờ duyệt',overview.facePending,ScanFace,'cyan'],['Fake GPS',overview.mockGps,MapPinned,'purple'],['Nghi né phí',overview.offPlatform,Ban,'red'],['Fraud case mở',overview.openCases,ShieldCheck,'blue']];
  return <div className="trust-page"><div className="future-page-head"><div><span className="future-eyebrow">TRUST · IDENTITY · FRAUD CONTROL</span><h1>Trust & Safety Control Center</h1><p>Identity, thiết bị, GPS integrity, off-platform risk và fraud case trong một trung tâm điều hành.</p></div><button className="future-btn primary" onClick={load} disabled={busy}><RefreshCw size={16}/>{busy?'Đang tải':'Làm mới'}</button></div>
    {error&&<div className="future-alert">{error}</div>}
    <div className="trust-stats">{stat.map(([label,value,Icon,tone])=><div className={`future-stat ${tone}`} key={label}><div><small>{label}</small><strong>{fmt(value)}</strong></div><span><Icon size={20}/></span></div>)}</div>
    <div className="future-card trust-scoreboard"><div className="future-card-head"><div><h2>Risk Score cao nhất</h2><p>Tài khoản cần ưu tiên kiểm tra</p></div><span className="future-live"><i/> LIVE RISK</span></div><div className="trust-profile-grid">{profiles.slice(0,8).map(x=><div className="trust-profile" key={x._id}><div className="risk-ring" data-level={x.riskLevel}><b>{x.riskScore||0}</b><small>/100</small></div><div><b>{x.subjectType} · {String(x.subjectId).slice(-8)}</b><span>{x.riskLevel} · {x.eventCount||0} sự kiện</span></div></div>)}</div></div>
    <div className="future-tabs"><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}>Risk Events</button><button className={tab==='cases'?'active':''} onClick={()=>setTab('cases')}>Fraud Cases</button><button className={tab==='face'?'active':''} onClick={()=>setTab('face')}>Face Verification</button><button className={tab==='devices'?'active':''} onClick={()=>setTab('devices')}>Trusted Devices</button><button className={tab==='rules'?'active':''} onClick={()=>setTab('rules')}>Risk Rules</button></div>
    {tab==='events'&&<div className="future-card"><div className="future-card-head"><div><h2>Risk Events</h2><p>Bằng chứng và tín hiệu rủi ro mới nhất</p></div></div><div className="future-table"><table><thead><tr><th>Loại</th><th>Đối tượng</th><th>Severity</th><th>Điểm</th><th>Booking</th><th>Thời gian</th></tr></thead><tbody>{events.map(x=><tr key={x._id}><td><b>{x.type}</b></td><td>{x.subjectType} · {String(x.subjectId).slice(-8)}</td><td><span className={`risk-badge ${String(x.severity).toLowerCase()}`}>{x.severity}</span></td><td>+{x.riskPoints}</td><td>{x.bookingId?String(x.bookingId).slice(-8):'—'}</td><td>{date(x.createdAt)}</td></tr>)}</tbody></table></div></div>}
    {tab==='cases'&&<div className="future-card"><div className="future-card-head"><div><h2>Fraud Cases</h2><p>Case vượt ngưỡng review</p></div></div><div className="future-table"><table><thead><tr><th>Case</th><th>Đối tượng</th><th>Risk</th><th>Ưu tiên</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{cases.map(x=><tr key={x._id}><td><b>{x.caseCode}</b></td><td>{x.subjectType} · {String(x.subjectId).slice(-8)}</td><td><b>{x.riskScore}</b></td><td>{x.priority}</td><td>{x.status}</td><td><div className="future-actions"><button onClick={()=>caseAction(x._id,'START_REVIEW')}>Review</button><button onClick={()=>caseAction(x._id,'RESOLVE')}>Resolve</button></div></td></tr>)}</tbody></table></div></div>}
    {tab==='face'&&<div className="future-card"><div className="future-card-head"><div><h2>Face & Liveness</h2><p>Xác thực Driver, thiết bị mới và step-up verification</p></div></div><div className="future-table"><table><thead><tr><th>Driver/User</th><th>Trigger</th><th>Liveness</th><th>Face match</th><th>Status</th><th>Review</th></tr></thead><tbody>{verify.map(x=><tr key={x._id}><td>{String(x.userId).slice(-10)}</td><td>{x.trigger}</td><td>{Math.round(Number(x.livenessScore||0)*100)}%</td><td>{Math.round(Number(x.faceMatchScore||0)*100)}%</td><td><span className={`risk-badge ${x.status==='PASSED'?'low':x.status==='FAILED'?'critical':'medium'}`}>{x.status}</span></td><td><div className="future-actions"><button onClick={()=>openEvidence(x._id).catch(e=>setError(e.message))}>Xem ảnh</button>{x.status==='REVIEW_REQUIRED'&&<><button className="ok" onClick={()=>review(x._id,'APPROVE')}><CheckCircle2 size={14}/> Duyệt</button><button className="danger" onClick={()=>review(x._id,'REJECT')}><XCircle size={14}/> Từ chối</button></>}</div></td></tr>)}</tbody></table></div></div>}
    {tab==='devices'&&<div className="future-card"><div className="future-card-head"><div><h2>Trusted Devices</h2><p>Thiết bị đã bind với User/Driver, App Check và xác thực sinh trắc học.</p></div></div><div className="future-table"><table><thead><tr><th>User</th><th>Role</th><th>Thiết bị</th><th>Integrity</th><th>Trusted</th><th>Biometric</th><th>Last seen</th><th></th></tr></thead><tbody>{devices.map(x=><tr key={x._id}><td>{String(x.userId).slice(-10)}</td><td>{x.role}</td><td><b>{x.model||x.deviceId}</b><br/><small>{x.platform} · {x.osVersion||'—'}</small></td><td><span className={`risk-badge ${x.integrity==='VERIFIED'?'low':'medium'}`}>{x.integrity||'UNKNOWN'}</span></td><td>{x.trusted?'YES':'NO'}</td><td>{date(x.biometricVerifiedAt)}</td><td>{date(x.lastSeenAt)}</td><td>{x.status!=='REVOKED'&&<button className="future-btn" onClick={()=>revokeDevice(x._id)}>Revoke</button>}</td></tr>)}</tbody></table></div></div>}
    {tab==='rules'&&<div className="future-card"><div className="future-card-head"><div><h2>Risk Rules</h2><p>Điều chỉnh trọng số rule mà không sửa source.</p></div></div><div className="future-table"><table><thead><tr><th>Rule</th><th>Enabled</th><th>Weight</th><th>Thao tác</th></tr></thead><tbody>{rules.map(x=><tr key={x._id}><td><b>{x.code}</b><br/><small>{x.name}</small></td><td>{x.enabled?'ON':'OFF'}</td><td>{x.weight}</td><td><div className="future-actions"><button onClick={()=>updateRule(x,{enabled:!x.enabled})}>{x.enabled?'Tắt':'Bật'}</button><button onClick={()=>{const v=window.prompt('Risk weight 0-100',String(x.weight||0));if(v!==null)updateRule(x,{weight:Number(v)})}}>Đổi weight</button></div></td></tr>)}</tbody></table></div></div>}
  </div>
}
